"""A module for defining enums used in the project."""

from .mc3d_types import Color, ColorInt, Limb


class COLORS:
    RED: Color =        (1.0,   0.0,    0.0,    1.0)
    GREEN: Color =      (0.0,   1.0,    0.0,    1.0)
    BLUE: Color =       (0.0,   0.0,    1.0,    1.0)
    LIGHT_BLUE: Color = (0.2,   0.6,    1.0,    1.0)
    PINK: Color =       (1.0,   0.2,    1.0,    1.0)
    ORANGE: Color =     (1.0,   0.5,    0.0,    1.0)
    BLACK: Color =      (0.0,   0.0,    0.0,    1.0)
    WHITE: Color =      (1.0,   1.0,    1.0,    1.0)


class COLORS_INT:
    RED: ColorInt =        (255,   0,      0,      255)
    GREEN: ColorInt =      (0,     255,    0,      255)
    BLUE: ColorInt =       (0,     0,      255,    255)
    LIGHT_BLUE: ColorInt = (51,    153,    255,    255)
    PINK: ColorInt =       (255,   51,     255,    255)
    ORANGE: ColorInt =     (255,   128,    0,      255)
    BLACK: ColorInt =      (0,     0,      0,      255)
    WHITE: ColorInt =      (255,   255,    255,    255)


class KPT_IDXS:
    NOSE = 0
    LEFT_EYE = 1
    RIGHT_EYE = 2
    LEFT_EAR = 3
    RIGHT_EAR = 4
    LEFT_SHOULDER = 5
    RIGHT_SHOULDER = 6
    LEFT_ELBOW = 7
    RIGHT_ELBOW = 8
    LEFT_HAND = 9
    RIGHT_HAND = 10
    LEFT_HIP = 11
    RIGHT_HIP = 12
    LEFT_KNEE = 13
    RIGHT_KNEE = 14
    LEFT_FOOT = 15
    RIGHT_FOOT = 16

class LIMB_IDXS:
    RIGHT_TEAR_THROUGH = 0
    LEFT_TEAR_THROUGH = 1
    EYEBROW = 2
    RIGHT_TEMPORAL = 3
    LEFT_TEMPORAL = 4
    RIGHT_NECKLINE = 5
    LEFT_NECKLINE = 6
    SHOULDER_LINE = 7
    RIGHT_BRACHIUM = 8
    LEFT_BRACHIUM = 9
    RIGHT_ANTEBRACHIUM = 10
    LEFT_ANTEBRACHIUM = 11
    RIGHT_TORSO = 12
    LEFT_TORSO = 13
    WAIST = 14
    RIGHT_THIGH = 15
    LEFT_THIGH = 16
    RIGHT_SHIN = 17
    LEFT_SHIN = 18

LIMB_KPTS: dict[int, list[int]] = {
    LIMB_IDXS.RIGHT_TEAR_THROUGH: [KPT_IDXS.NOSE, KPT_IDXS.RIGHT_EYE],
    LIMB_IDXS.LEFT_TEAR_THROUGH: [KPT_IDXS.NOSE, KPT_IDXS.LEFT_EYE],
    LIMB_IDXS.EYEBROW: [KPT_IDXS.RIGHT_EYE, KPT_IDXS.LEFT_EYE],
    LIMB_IDXS.RIGHT_TEMPORAL: [KPT_IDXS.RIGHT_EYE, KPT_IDXS.RIGHT_EAR],
    LIMB_IDXS.LEFT_TEMPORAL: [KPT_IDXS.LEFT_EYE, KPT_IDXS.LEFT_EAR],
    LIMB_IDXS.RIGHT_NECKLINE: [KPT_IDXS.RIGHT_EAR, KPT_IDXS.RIGHT_SHOULDER],
    LIMB_IDXS.LEFT_NECKLINE: [KPT_IDXS.LEFT_EAR, KPT_IDXS.LEFT_SHOULDER],
    LIMB_IDXS.SHOULDER_LINE: [KPT_IDXS.RIGHT_SHOULDER, KPT_IDXS.LEFT_SHOULDER],
    LIMB_IDXS.RIGHT_BRACHIUM: [KPT_IDXS.RIGHT_SHOULDER, KPT_IDXS.RIGHT_ELBOW],
    LIMB_IDXS.LEFT_BRACHIUM: [KPT_IDXS.LEFT_SHOULDER, KPT_IDXS.LEFT_ELBOW],
    LIMB_IDXS.RIGHT_ANTEBRACHIUM: [KPT_IDXS.RIGHT_ELBOW, KPT_IDXS.RIGHT_HAND],
    LIMB_IDXS.LEFT_ANTEBRACHIUM: [KPT_IDXS.LEFT_ELBOW, KPT_IDXS.LEFT_HAND],
    LIMB_IDXS.RIGHT_TORSO: [KPT_IDXS.RIGHT_SHOULDER, KPT_IDXS.RIGHT_HIP],
    LIMB_IDXS.LEFT_TORSO: [KPT_IDXS.LEFT_SHOULDER, KPT_IDXS.LEFT_HIP],
    LIMB_IDXS.WAIST: [KPT_IDXS.RIGHT_HIP, KPT_IDXS.LEFT_HIP],
    LIMB_IDXS.RIGHT_THIGH: [KPT_IDXS.RIGHT_HIP, KPT_IDXS.RIGHT_KNEE],
    LIMB_IDXS.LEFT_THIGH: [KPT_IDXS.LEFT_HIP, KPT_IDXS.LEFT_KNEE],
    LIMB_IDXS.RIGHT_SHIN: [KPT_IDXS.RIGHT_KNEE, KPT_IDXS.RIGHT_FOOT],
    LIMB_IDXS.LEFT_SHIN: [KPT_IDXS.LEFT_KNEE, KPT_IDXS.LEFT_FOOT]
}

KPT_COLORS: dict[int, Color] = {
    KPT_IDXS.NOSE: COLORS.GREEN,
    KPT_IDXS.RIGHT_EYE: COLORS.GREEN,
    KPT_IDXS.LEFT_EYE: COLORS.GREEN,
    KPT_IDXS.RIGHT_EAR: COLORS.GREEN,
    KPT_IDXS.LEFT_EAR: COLORS.GREEN,
    KPT_IDXS.RIGHT_SHOULDER: COLORS.LIGHT_BLUE,
    KPT_IDXS.LEFT_SHOULDER: COLORS.LIGHT_BLUE,
    KPT_IDXS.RIGHT_ELBOW: COLORS.LIGHT_BLUE,
    KPT_IDXS.LEFT_ELBOW: COLORS.LIGHT_BLUE,
    KPT_IDXS.RIGHT_HAND: COLORS.LIGHT_BLUE,
    KPT_IDXS.LEFT_HAND: COLORS.LIGHT_BLUE,
    KPT_IDXS.RIGHT_HIP: COLORS.ORANGE,
    KPT_IDXS.LEFT_HIP: COLORS.ORANGE,
    KPT_IDXS.RIGHT_KNEE: COLORS.ORANGE,
    KPT_IDXS.LEFT_KNEE: COLORS.ORANGE,
    KPT_IDXS.RIGHT_FOOT: COLORS.ORANGE,
    KPT_IDXS.LEFT_FOOT: COLORS.ORANGE
}

LIMB_COLORS: dict[int, Color] = {
    LIMB_IDXS.RIGHT_TEAR_THROUGH: COLORS.GREEN,
    LIMB_IDXS.LEFT_TEAR_THROUGH: COLORS.GREEN,
    LIMB_IDXS.EYEBROW: COLORS.GREEN,
    LIMB_IDXS.RIGHT_TEMPORAL: COLORS.GREEN,
    LIMB_IDXS.LEFT_TEMPORAL: COLORS.GREEN,
    LIMB_IDXS.RIGHT_NECKLINE: COLORS.GREEN,
    LIMB_IDXS.LEFT_NECKLINE: COLORS.GREEN,
    LIMB_IDXS.SHOULDER_LINE: COLORS.LIGHT_BLUE,
    LIMB_IDXS.RIGHT_BRACHIUM: COLORS.LIGHT_BLUE,
    LIMB_IDXS.LEFT_BRACHIUM: COLORS.LIGHT_BLUE,
    LIMB_IDXS.RIGHT_ANTEBRACHIUM: COLORS.LIGHT_BLUE,
    LIMB_IDXS.LEFT_ANTEBRACHIUM: COLORS.LIGHT_BLUE,
    LIMB_IDXS.RIGHT_TORSO: COLORS.PINK,
    LIMB_IDXS.LEFT_TORSO: COLORS.PINK,
    LIMB_IDXS.WAIST: COLORS.PINK,
    LIMB_IDXS.RIGHT_THIGH: COLORS.ORANGE,
    LIMB_IDXS.LEFT_THIGH: COLORS.ORANGE,
    LIMB_IDXS.RIGHT_SHIN: COLORS.ORANGE,
    LIMB_IDXS.LEFT_SHIN: COLORS.ORANGE
}

LIMBS: list[Limb] = [
    (LIMB_KPTS[LIMB_IDXS.RIGHT_TEAR_THROUGH], LIMB_COLORS[LIMB_IDXS.RIGHT_TEAR_THROUGH]),
    (LIMB_KPTS[LIMB_IDXS.LEFT_TEAR_THROUGH], LIMB_COLORS[LIMB_IDXS.LEFT_TEAR_THROUGH]),
    (LIMB_KPTS[LIMB_IDXS.EYEBROW], LIMB_COLORS[LIMB_IDXS.EYEBROW]),
    (LIMB_KPTS[LIMB_IDXS.RIGHT_TEMPORAL], LIMB_COLORS[LIMB_IDXS.RIGHT_TEMPORAL]),
    (LIMB_KPTS[LIMB_IDXS.LEFT_TEMPORAL], LIMB_COLORS[LIMB_IDXS.LEFT_TEMPORAL]),
    (LIMB_KPTS[LIMB_IDXS.RIGHT_NECKLINE], LIMB_COLORS[LIMB_IDXS.RIGHT_NECKLINE]),
    (LIMB_KPTS[LIMB_IDXS.LEFT_NECKLINE], LIMB_COLORS[LIMB_IDXS.LEFT_NECKLINE]),
    (LIMB_KPTS[LIMB_IDXS.SHOULDER_LINE], LIMB_COLORS[LIMB_IDXS.SHOULDER_LINE]),
    (LIMB_KPTS[LIMB_IDXS.RIGHT_BRACHIUM], LIMB_COLORS[LIMB_IDXS.RIGHT_BRACHIUM]),
    (LIMB_KPTS[LIMB_IDXS.LEFT_BRACHIUM], LIMB_COLORS[LIMB_IDXS.LEFT_BRACHIUM]),
    (LIMB_KPTS[LIMB_IDXS.RIGHT_ANTEBRACHIUM], LIMB_COLORS[LIMB_IDXS.RIGHT_ANTEBRACHIUM]),
    (LIMB_KPTS[LIMB_IDXS.LEFT_ANTEBRACHIUM], LIMB_COLORS[LIMB_IDXS.LEFT_ANTEBRACHIUM]),
    (LIMB_KPTS[LIMB_IDXS.RIGHT_TORSO], LIMB_COLORS[LIMB_IDXS.RIGHT_TORSO]),
    (LIMB_KPTS[LIMB_IDXS.LEFT_TORSO], LIMB_COLORS[LIMB_IDXS.LEFT_TORSO]),
    (LIMB_KPTS[LIMB_IDXS.WAIST], LIMB_COLORS[LIMB_IDXS.WAIST]),
    (LIMB_KPTS[LIMB_IDXS.RIGHT_THIGH], LIMB_COLORS[LIMB_IDXS.RIGHT_THIGH]),
    (LIMB_KPTS[LIMB_IDXS.LEFT_THIGH], LIMB_COLORS[LIMB_IDXS.LEFT_THIGH]),
    (LIMB_KPTS[LIMB_IDXS.RIGHT_SHIN], LIMB_COLORS[LIMB_IDXS.RIGHT_SHIN]),
    (LIMB_KPTS[LIMB_IDXS.LEFT_SHIN], LIMB_COLORS[LIMB_IDXS.LEFT_SHIN])
]

# from https://exrx.net/Kinesiology/Segments
# Total Height	173.3
# Forearm	15.85	27.46805
# Upper Arm	17.25	29.89425
# Thigh	24.05	41.67865
# Leg	25.2	43.6716
# Shoulders	22.25	38.55925
# Hips	11.65	20.18945
# Neck	10.75	18.62975
# Trunk	29.5	51.1235
# http://oandplibrary.org/al/pdf/1964_01_044.pdf

CONNECTIONS_TO_CHECK: list[tuple[int, int, float, float]] = [
    (KPT_IDXS.NOSE, KPT_IDXS.RIGHT_SHOULDER, 18.6, 20.0),
    (KPT_IDXS.NOSE, KPT_IDXS.LEFT_SHOULDER, 18.6, 20.0),
    (KPT_IDXS.RIGHT_SHOULDER, KPT_IDXS.LEFT_SHOULDER, 38.6, 21.0),
    (KPT_IDXS.RIGHT_SHOULDER, KPT_IDXS.RIGHT_ELBOW, 29.9, 20.0),
    (KPT_IDXS.RIGHT_SHOULDER, KPT_IDXS.RIGHT_HIP, 51.1, 22.0),
    (KPT_IDXS.LEFT_SHOULDER, KPT_IDXS.LEFT_ELBOW, 29.9, 21.0),
    (KPT_IDXS.LEFT_SHOULDER, KPT_IDXS.LEFT_HIP, 51.1, 22.0),
    (KPT_IDXS.RIGHT_ELBOW, KPT_IDXS.RIGHT_HAND, 27.5, 20.0),
    (KPT_IDXS.LEFT_ELBOW, KPT_IDXS.LEFT_HAND, 27.5, 20.0),
    (KPT_IDXS.RIGHT_HIP, KPT_IDXS.LEFT_HIP, 20.2, 20.0),
    (KPT_IDXS.RIGHT_HIP, KPT_IDXS.RIGHT_KNEE, 41.7, 20.0),
    (KPT_IDXS.LEFT_HIP, KPT_IDXS.LEFT_KNEE, 41.7, 20.0),
    (KPT_IDXS.RIGHT_KNEE, KPT_IDXS.RIGHT_FOOT, 43.7, 20.0),
    (KPT_IDXS.LEFT_KNEE, KPT_IDXS.LEFT_FOOT, 43.7, 20.0),
]


KPT_NAMES: dict[int, str] = {
    KPT_IDXS.NOSE: 'nose',
    KPT_IDXS.RIGHT_EYE: 'right eye',
    KPT_IDXS.LEFT_EYE: 'left eye',
    KPT_IDXS.RIGHT_EAR: 'right ear',
    KPT_IDXS.LEFT_EAR: 'left ear',
    KPT_IDXS.RIGHT_SHOULDER: 'right shoulder',
    KPT_IDXS.LEFT_SHOULDER: 'left shoulder',
    KPT_IDXS.RIGHT_ELBOW: 'right elbow',
    KPT_IDXS.LEFT_ELBOW: 'left elbow',
    KPT_IDXS.RIGHT_HAND: 'right hand',
    KPT_IDXS.LEFT_HAND: 'left hand',
    KPT_IDXS.RIGHT_HIP: 'right hip',
    KPT_IDXS.LEFT_HIP: 'left hip',
    KPT_IDXS.RIGHT_KNEE: 'right knee',
    KPT_IDXS.LEFT_KNEE: 'left knee',
    KPT_IDXS.RIGHT_FOOT: 'right foot',
    KPT_IDXS.LEFT_FOOT: 'left foot'
}


KPT_NAMES_SHORT: dict[int, str] = {
    KPT_IDXS.NOSE: 'nose',
    KPT_IDXS.RIGHT_EYE: 'r. eye',
    KPT_IDXS.LEFT_EYE: 'l. eye',
    KPT_IDXS.RIGHT_EAR: 'r. ear',
    KPT_IDXS.LEFT_EAR: 'l. ear',
    KPT_IDXS.RIGHT_SHOULDER: 'r. shoulder',
    KPT_IDXS.LEFT_SHOULDER: 'l. shoulder',
    KPT_IDXS.RIGHT_ELBOW: 'r. elbow',
    KPT_IDXS.LEFT_ELBOW: 'l. elbow',
    KPT_IDXS.RIGHT_HAND: 'r. hand',
    KPT_IDXS.LEFT_HAND: 'l. hand',
    KPT_IDXS.RIGHT_HIP: 'r. hip',
    KPT_IDXS.LEFT_HIP: 'l. hip',
    KPT_IDXS.RIGHT_KNEE: 'r. knee',
    KPT_IDXS.LEFT_KNEE: 'l. knee',
    KPT_IDXS.RIGHT_FOOT: 'r. foot',
    KPT_IDXS.LEFT_FOOT: 'l. foot'
}


KPT_NAMES_SHORTER: dict[int, str] = {
    KPT_IDXS.NOSE: '',
    KPT_IDXS.RIGHT_EYE: '',
    KPT_IDXS.LEFT_EYE: '',
    KPT_IDXS.RIGHT_EAR: '',
    KPT_IDXS.LEFT_EAR: '',
    KPT_IDXS.RIGHT_SHOULDER: '',
    KPT_IDXS.LEFT_SHOULDER: '',
    KPT_IDXS.RIGHT_ELBOW: 'right',
    KPT_IDXS.LEFT_ELBOW: 'left',
    KPT_IDXS.RIGHT_HAND: '',
    KPT_IDXS.LEFT_HAND: '',
    KPT_IDXS.RIGHT_HIP: '',
    KPT_IDXS.LEFT_HIP: '',
    KPT_IDXS.RIGHT_KNEE: '',
    KPT_IDXS.LEFT_KNEE: '',
    KPT_IDXS.RIGHT_FOOT: '',
    KPT_IDXS.LEFT_FOOT: ''
}
